# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h09pzZDlEpGecNw8qR2Nf-NDBALcmjw2
"""

#inputkan 3 buah nilai yang di pisahkan dengan koma
#output = nilai1^2 + nilai2^2 + nilai3^2

#display result
x1,x2,x3 = eval(input("Masukkan 3 angka dipisahkan dengan koma = "))
print('Jumlah kuadrat dari 3 angka yang anda masukkan adalah',x1**2+x2**2+x3**2)
